version: '3'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=morris-frank.dev
      - SUBDOMAINS=vault,watch,cloud,
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - ONLY_SUBDOMAINS=true
    volumes:
      - ~/appdata/swag:/config
    ports:
      - 443:443
    restart: unless-stopped
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
    volumes:
      - ~/appdata/vaultwarden:/data
  filestash:
    container_name: filestash
    image: machines/filestash
    restart: always
    environment:
      - APPLICATION_URL=cloud.morris-frank.dev
    volumes:
      - ~/appdata/filestash:/app/data/state/config
    ports:
      - "8334:8334"