version: "3"

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=morris-frank.dev
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ~/appdata/swag:/config
    ports:
      - 443:443
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:127.0.0.1
  soilytix:
    image: joseluisq/static-web-server:2
    volumes:
      - /root/soilytix:/public
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
    volumes:
      - ~/appdata/vaultwarden:/data
